### ISSUE TITLE
算错了！

### ISSUE THREAD

**Issue by pzklr** [jjonline/calendar.js#11]
1933年7月22日 是 闰五月三十。

**Comment by jjonline** [comment]
查了下百度的农历，返回的是农历六月初一，农历天数"表"可能有问题，如果确认有问题，那么至少有两个有问题，得空核对下

**Comment by MrNeptune** [comment]
"1933-7-22,1933-7-23,1933-7-24,1933-7-25,1933-7-26,1933-7-27,1933-7-28,1933-7-29,1933-7-30,1933-7-31,1933-8-1,1933-8-2,1933-8-3,1933-8-4,1933-8-5,1933-8-6,1933-8-7,1933-8-8,1933-8-9,1933-8-10,1933-8-11,1933-8-12,1933-8-13,1933-8-14,1933-8-15,1933-8-16,1933-8-17,1933-8-18,1933-8-19,1933-8-20,2057-9-28,2057-9-29,2057-9-30,2057-10-1,2057-10-2,2057-10-3,2057-10-4,2057-10-5,2057-10-6,2057-10-7,2057-10-8,2057-10-9,2057-10-10,2057-10-11,2057-10-12,2057-10-13,2057-10-14,2057-10-15,2057-10-16,2057-10-17,2057-10-18,2057-10-19,2057-10-20,2057-10-21,2057-10-22,2057-10-23,2057-10-24,2057-10-25,2057-10-26,2057-10-27,2060-4-30,2060-5-1,2060-5-2,2060-5-3,2060-5-4,2060-5-5,2060-5-6,2060-5-7,2060-5-8,2060-5-9,2060-5-10,2060-5-11,2060-5-12,2060-5-13,2060-5-14,2060-5-15,2060-5-16,2060-5-17,2060-5-18,2060-5-19,2060-5-20,2060-5-21,2060-5-22,2060-5-23,2060-5-24,2060-5-25,2060-5-26,2060-5-27,2060-5-28,2060-5-29,"

**Comment by MrNeptune** [comment]
以上这些都对不上，看着办。

**Comment by MrNeptune** [comment]
java项目
https://github.com/heqiao2010/LunarCalendar

**Comment by MrNeptune** [comment]
不更新吗？

**Comment by panjp-git** [comment]
按香港天文台数据，1933年
0x06e95
得改为
0x16a95
即改动：
1933年 闰五月三十
1933年 六月廿九（没有三十）
百度应该也是按照这数据算的

至于2057年，香港天文台自己都说了：
“由于计算数十年后的月相及节气时间可能会有数分钟的误差，若新月(即农历初一)或节气时间很接近午夜零时，「对照表」内相关农历月份或节气的日期可能会有一日之差别。这些情况会出现在2057年9月28日、2089年9月4日及2097年8月7日的新月、2021年的冬至、2051年的春分、2083年的立春和2084年的春分。”
https://www.weather.gov.hk/sc/gts/time/conversion.htm

只有到那时才能确定这些年份农历是否有误。

**Comment by jjonline** [comment]
接收PR，如果您知道怎么改，可以改了发PR，感谢

**Comment by panjp-git** [comment]
PR已发，修正1933/2060年；
2057年有争议（2057-9-28 手机上日历显示八月三十，微软日历显示九月初一），暂不做修改

**Comment by agxuj** [comment]
不是参考香港天文台吗？去网站上看一看不就OK了吗？

**Comment by agxuj** [comment]
https://www.hko.gov.hk/

**Comment by jjonline** [comment]
PR link # https://github.com/jjonline/calendar.js/pull/12
