### ISSUE TITLE
import 报错改怎么改

### ISSUE THREAD

**Issue by wanghai1** [jjonline/calendar.js#15]
C:\Users\25166\Desktop\vue\fullcalendar-example-projects\vue-vuex\src\assets\calendar.js
  417:13  error  Unreachable code                                 no-unreachable
  420:13  error  Unreachable code                                 no-unreachable
  462:17  error  'objDate' is already defined                     no-redeclare
  466:13  error  'y' is already defined                           no-redeclare
  467:13  error  'm' is already defined                           no-redeclare
  468:13  error  'd' is already defined                           no-redeclare
  493:13  error  'leap' is already defined                        no-redeclare
  608:13  error  'isLeapMonth' is already defined                 no-redeclare
  609:13  error  'leapOffset' is assigned a value but never used  no-unused-vars
  611:13  error  'leapDay' is assigned a value but never used     no-unused-vars
  629:17  error  'i' is already defined                           no-redeclare

**Comment by jjonline** [comment]
多年前写的代码，当前严格的ES语法检查已经通不过了，您可以改造提交PR，接收PR合并，感谢支持
