### ISSUE TITLE
大佬，我想显示每天是周几能在这个基础扩展吗？

### ISSUE THREAD

**Issue by newsun007** [jjonline/calendar.js#16]
大佬，我想显示每天是周几能在这个基础扩展吗？期待你的回复，万分感谢

**Comment by jjonline** [comment]
[https://github.com/jjonline/calendar.js/blob/master/calendar.js#L587-L588](https://github.com/jjonline/calendar.js/blob/master/calendar.js#L587-L588) 周几库有返回，这里，感谢支持

**Comment by newsun007** [comment]
这边阴阳历的切换，重复点击会有Bug,日期一直变请问这个能解决吗？就是tab栏的切换，你重复点击日期会变
