### ISSUE TITLE
重复点击tab栏，日期会发生变化，请问怎样解决？

### ISSUE THREAD

**Issue by newsun007** [jjonline/calendar.js#17]
重复点击tab栏，日期会发生变化，重复点击tab栏的阴历或者阳历，日期会一直变化，请问怎么解决？

**Comment by jjonline** [comment]
这个库没有提供ui界面方面的功能，仅仅是公历农历相互转换；重复点击的问题请自行检查引用的对应的库或者排查相关event代码，感谢支持
