### ISSUE TITLE
传参问题

### ISSUE THREAD

**Issue by LiuQixuan** [jjonline/calendar.js#18]
看了源码才发现传入的月份为1-12(含12),即自然月表示法.
然而,js原生的Date()对象的月份是0-11(含11)即自然月-1.既然js标准我们改变不了,那为什么不去适应它呢.这边调用函数month+1,传入参数再month-1图个啥呢.很多时候就直接传参了,导致非常复杂的bug改起来那叫一个酸爽.

**Comment by jjonline** [comment]
接收PR合并，您可以提交您的修改代码合并进去，感谢支持
