### ISSUE TITLE
支持大佬，大佬牛掰

### ISSUE THREAD

**Issue by ShyZhen** [jjonline/calendar.js#21]
如题

**Comment by jjonline** [comment]
想在这儿露脸么？你还不如发个PR过来改进下这个项目，我这小庙露脸也没啥用啊~  哈哈

**Comment by ShyZhen** [comment]
> 想在这儿露脸么？你还不如发个PR过来改进下这个项目，我这小庙露脸也没啥用啊~ 哈哈

实力不允许啊，哈哈哈
