### ISSUE TITLE
发现两个问题，已经提交pr

### ISSUE THREAD

**Issue by qq1871508593** [jjonline/calendar.js#26]
初次使用这个插件，没有作任何修改，发现有以下两个问题：![image](https://user-images.githubusercontent.com/49339389/144834267-34cf7a37-6513-4357-b4d2-bc317c2effa8.png)1、每月最后一天和下个月的第一天，比如31号跟1号，显示出的农历信息重复
2、获取到的节气是错误的
如图：

我以为是我传参问题，但是不论我怎么修改，都无法正确的显示相应信息。后查看源码，发现部分逻辑存在错误之处，已经在pr中做修改#25。

以上修改都经过验证，已经能拿到正确信息。第一次提pr，不太懂操作，如果pr代码中或者提交操作上有不妥之处，望指出，我会及时更改。

**Comment by jjonline** [comment]
感谢PR，发布PR后PR里也是具有回帖和谈论功能的，不必再次发布Issues，直接在PR里讨论回帖即可~
---
PR已做讨论回复请检查对应PR，该Issues就关闭了
再次感谢您的PR让这个项目变更的更好~
