### ISSUE TITLE
关于 getTerm

### ISSUE THREAD

**Issue by ICE99125** [jjonline/calendar.js#32]
var _24 = calendar.getTerm(1987,3) ; // _24=4;意即1987年2月4日立春

想问下 2 月是怎么得到的

**Comment by jjonline** [comment]
详见评论里回复：[https://blog.jjonline.cn/userInterFace/173.html/comment-page-6#comments](https://blog.jjonline.cn/userInterFace/173.html/comment-page-6#comments)
