### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by liaoyajun** [jjonline/calendar.js#4]
哈喽，作者大佬你好。
我在使用您的插件中发现阳历1996-10-1对应的农历应该是八月十九，但是插件的计算结果是八月二十
1996这年的0x055c0应该是0x05ac0

**Comment by jjonline** [comment]
应该是表的问题，您可以提交一个pull request，我这边儿合并一下即可，这样您的提交就在贡献者里～

**Comment by liaoyajun** [comment]
好的

**Comment by jjonline** [comment]
ok  已合并  这issue关闭了
